#!/bin/bash -l 
COMMNAME=DNS_HIT 
#SBATCH --job-name=${COMMNAME} --time=24:00:00 
#SBATCH --output=out.txt --error=err.txt --constraint=gpu 
#SBATCH --account=929 --partition=normal 
#SBATCH --array=0-239 --ntasks-per-node=1 
ind=$SLURM_ARRAY_TASK_ID 
RUNDIRN=`./launchAllHIT.py --case ${ind} --printName` 
OPTIONS=`./launchAllHIT.py --case ${ind} --printOptions` 
mkdir -p ${SCRATCH}/CubismUP3D/${RUNDIRN} 
cd ${SCRATCH}/CubismUP3D/${RUNDIRN} 
cp ${HOME}/CubismUP_3D/bin/simulation ./exec 
export OMP_NUM_THREADS=12 
export CRAY_CUDA_MPS=1 
srun --ntasks 1 --ntasks-per-node=1 ./exec ${OPTIONS} 
