/* Compile-time settings. Generated by CMake. */
#ifndef CUBISMUP3D_MACROS_H_GENERATED
#define CUBISMUP3D_MACROS_H_GENERATED

// https://cmake.org/cmake/help/latest/command/configure_file.html

#define CUP_ALIGNMENT  64
#define CUP_BLOCK_SIZE ${BLOCK_SIZE}
#define CUBISM_USE_HDF

#cmakedefine01 CUP_IS_MPI_THREAD_UNSAFE
#if !(CUP_IS_MPI_THREAD_UNSAFE)
// Async hdf5 dump disabled if MPI is not thread safe.
#cmakedefine CUP_ASYNC_DUMP
#endif
#cmakedefine CUP_DUMP_SURFACE_BINARY
#cmakedefine CUP_SINGLE_PRECISION
#cmakedefine CUP_HDF5_DOUBLE_PRECISION
#cmakedefine CUP_VERBOSE

#endif
